README.md, package-lock.json, package.json, src/cheerioManipulation.js, src/formatMarkup.js, src/loadOptions.js, tests/mockComponents/InlineFunctions.vue, tests/mockComponents/StringifyAttributes.vue, tests/mockComponents/StringifyProps.vue, tests/unit/index.test.js, tests/unit/src/__snapshots__/cheerioManipulation.test.js.snap, tests/unit/src/cheerioManipulation.test.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js, vitest.config.js
Closes #2
* ~Experimental branch~
* Experiment was a success
**Checklist:**
=> Add and remove serializer keys for attribute mapping

src/formatMarkup.js, src/loadOptions.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
=> Rename showEmptyAttributes to emptyAttributes

src/formatMarkup.js, src/loadOptions.js, tests/unit/src/__snapshots__/cheerioManipulation.test.js.snap, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
Closes #12
*  Contains code to implement self-closing tags functionality based on formatting object passed.
* Optimized self-closing code and fixed some errors by making formatting option values consistent throughout the code.
* @TheJaredWilcurt . please have a look.
=> Added code to implement self closing tags functionality

src/formatMarkup.js, src/loadOptions.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
Closes #15 
* Added code to preserve white Spaces in tags based on options passed.
**Checklist:**
=> feat: Preserve WhiteSpace in Tags

package-lock.json, package.json, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
=> Bump, Deps, Lint

package-lock.json, package.json, src/loadOptions.js, tests/unit/src/loadOptions.test.js
=> Load options improvements

src/formatMarkup.js, src/loadOptions.js, tests/unit/src/cheerioManipulation.test.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
Related to issue #32
*
**Checklist:**
=> Refactor formatting options to global.vueSnapshots.formatting

package-lock.json, package.json, src/formatMarkup.js, src/loadOptions.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js, types.js
=> closingTag to xml

package-lock.json, package.json, src/helpers.js, tests/unit/src/formatMarkup.test.js
=> Non-breaking spaces and quotes in HTML entity encoding

package-lock.json, package.json, src/formatMarkup.js, tests/unit/src/formatMarkup.test.js
=> Format SVGs similar to void elements

package-lock.json, package.json, src/formatMarkup.js, src/loadOptions.js, tests/unit/src/formatMarkup.test.js, tests/unit/src/loadOptions.test.js
=> Simplify preserve whitespace in tags feature

package-lock.json, package.json, src/formatMarkup.js, tests/unit/src/formatMarkup.test.js, types.js
=> Child of whitespace dependent tags

package-lock.json, package.json, src/formatMarkup.js, tests/unit/src/formatMarkup.test.js
=> Nested attribute indentation on whitespace preserved children

package-lock.json, package.json, src/formatMarkup.js, tests/unit/src/formatMarkup.test.js
=> SVG filters

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, package.json, src/cheerioManipulation.js, tests/mockComponents/CheckboxesAndRadios.vue, tests/unit/src/cheerioManipulation.test.js
=> Checkbox and radios checked

eslint.config.js, package-lock.json, package.json
Related to issue #0
*
**Checklist:**
=> ESlint Vitest

package-lock.json, package.json, src/cheerioManipulation.js
=> Release prep

index.js, package-lock.json, package.json, src/cheerioManipulation.js, src/helpers.js, tests/mockComponents/TestingLibrary.vue, tests/unit/index.test.js, tests/unit/src/__snapshots__/cheerioManipulation.test.js.snap, tests/unit/src/__snapshots__/testingLibrary.test.js.snap, tests/unit/src/cheerioManipulation.test.js, tests/unit/src/testingLibrary.test.js
Adds support for
```js
const { container } = render(MyComponent);
expect(container)
.toMatchSnapshot();
```
**Checklist:**
=> @Testing-Library/Vue containers

package-lock.json, package.json, src/helpers.js, tests/unit/src/__snapshots__/cheerioManipulation.test.js.snap, tests/unit/src/__snapshots__/testingLibrary.test.js.snap, tests/unit/src/helpers.test.js
=> Stringify Attributes improvements

package-lock.json, package.json, src/formatters/diffable.js, src/helpers.js, src/loadOptions.js, tests/unit/src/cheerioManipulation.test.js, tests/unit/src/formatters/diffable.test.js, tests/unit/src/helpers.test.js, tests/unit/src/loadOptions.test.js, types.js
=> Inline styles

package-lock.json, package.json
=> Update devDependencies, Volta

package-lock.json, package.json, src/cheerioManipulation.js, src/loadOptions.js, tests/unit/src/cheerioManipulation.test.js, tests/unit/src/loadOptions.test.js, types.js
=> regexToRemoveAttributes
